-- MySQL Script generated by MySQL Workbench
-- Sat Dec 15 02:21:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcc` DEFAULT CHARACTER SET utf8 ;
USE `sgcc` ;

-- -----------------------------------------------------
-- Table `sgcc`.`dictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`dictamen` (
  `identificadordictamen` VARCHAR(45) NOT NULL,
  `tipoDictamen` VARCHAR(45) NULL DEFAULT NULL,
  `descripciondictamen` VARCHAR(50) NULL DEFAULT NULL,
  `descripcionproblema` VARCHAR(45) NULL DEFAULT NULL,
  `tipomantenimiento` VARCHAR(45) NULL DEFAULT NULL,
  `tipofalla` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`identificadordictamen`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`software`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`software` (
  `idSoftware` VARCHAR(45) NOT NULL,
  `nombreSoftware` VARCHAR(45) NOT NULL,
  `origen` VARCHAR(45) NULL DEFAULT NULL,
  `Observaciones` TEXT NULL DEFAULT NULL,
  `fechaAdquisicion` DATE NULL DEFAULT NULL,
  `tipoSoftware` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `requiereActualizacion` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idSoftware`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`licencia` (
  `idlicencia` VARCHAR(40) NOT NULL,
  `nombreLicencia` VARCHAR(45) NOT NULL,
  `fechaVigencia` DATE NULL DEFAULT NULL,
  `fechaAdquisicion` DATE NULL DEFAULT NULL,
  `tipoLicenciamiento` VARCHAR(45) NULL DEFAULT NULL,
  `Software_idSoftware` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlicencia`),
  INDEX `fk_Licencia_Software1_idx` (`Software_idSoftware` ASC) VISIBLE,
  CONSTRAINT `fk_Licencia_Software1`
    FOREIGN KEY (`Software_idSoftware`)
    REFERENCES `sgcc`.`software` (`idSoftware`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`hardware`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`hardware` (
  `numeroinventario` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `marca` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `modelo` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `numeroserie` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tipodispositivo` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ubicacion` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fechaadquisicion` DATE NULL DEFAULT NULL,
  `estado` BIT(1) NULL DEFAULT NULL,
  `partesdispositivo` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Licencia_claveLicencia` VARCHAR(40) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`numeroinventario`),
  INDEX `fk_Hardware_Licencia1_idx` (`Licencia_claveLicencia` ASC) VISIBLE,
  CONSTRAINT `fk_Hardware_Licencia1`
    FOREIGN KEY (`Licencia_claveLicencia`)
    REFERENCES `sgcc`.`licencia` (`idlicencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `sgcc`.`hardware_dictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`hardware_dictamen` (
  `dictamen` VARCHAR(45) NOT NULL,
  `dictamen_identificadordictamen` VARCHAR(45) NOT NULL,
  `hardware_numeroinventario` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`dictamen`),
  INDEX `dictamen_idx` (`dictamen` ASC) VISIBLE,
  INDEX `fk_hardware_dictamen_dictamen1_idx` (`dictamen_identificadordictamen` ASC) VISIBLE,
  INDEX `fk_hardware_dictamen_hardware1_idx` (`hardware_numeroinventario` ASC) VISIBLE,
  CONSTRAINT `fk_hardware_dictamen_dictamen1`
    FOREIGN KEY (`dictamen_identificadordictamen`)
    REFERENCES `sgcc`.`dictamen` (`identificadordictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hardware_dictamen_hardware1`
    FOREIGN KEY (`hardware_numeroinventario`)
    REFERENCES `sgcc`.`hardware` (`numeroinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`responsables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`responsables` (
  `matriculaempleado` VARCHAR(45) NOT NULL,
  `nombrecompleto` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `correoinstitucional` VARCHAR(45) NULL DEFAULT NULL,
  `estado` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`matriculaempleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`resguardos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`resguardos` (
  `hardware` VARCHAR(50) NOT NULL,
  `fechaResguardo` DATE NULL DEFAULT NULL,
  `responsables_matriculaempleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hardware`),
  INDEX `fk_resguardos_responsables1_idx` (`responsables_matriculaempleado` ASC) VISIBLE,
  CONSTRAINT `hardwarePrestado`
    FOREIGN KEY (`hardware`)
    REFERENCES `sgcc`.`hardware` (`numeroinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resguardos_responsables1`
    FOREIGN KEY (`responsables_matriculaempleado`)
    REFERENCES `sgcc`.`responsables` (`matriculaempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`softwareversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`softwareversion` (
  `version` INT(11) NULL DEFAULT NULL,
  `enUso` TINYINT(1) NULL DEFAULT NULL,
  `idioma` VARCHAR(45) NULL DEFAULT NULL,
  `sistemaOperativo` VARCHAR(45) NULL DEFAULT NULL,
  `idversion` INT(11) NOT NULL AUTO_INCREMENT,
  `Software_idSoftware` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idversion`),
  INDEX `fk_softwareVersion_Software1_idx` (`Software_idSoftware` ASC) VISIBLE,
  CONSTRAINT `fk_softwareVersion_Software1`
    FOREIGN KEY (`Software_idSoftware`)
    REFERENCES `sgcc`.`software` (`idSoftware`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sgcc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcc`.`usuario` (
  `idnumeropersonal` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `contraseña` VARCHAR(255) NULL DEFAULT NULL,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `correoinstitucional` VARCHAR(45) NULL DEFAULT NULL,
  `rol` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `Dictamen_idDictamen` VARCHAR(45) NULL DEFAULT NULL,
  `estado` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idnumeropersonal`),
  INDEX `fk_Usuario_Dictamen1_idx` (`Dictamen_idDictamen` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Dictamen1`
    FOREIGN KEY (`Dictamen_idDictamen`)
    REFERENCES `sgcc`.`dictamen` (`identificadordictamen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
